# Generated by Django 3.1 on 2020-08-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseholdDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100)),
                ('spouse_name', models.CharField(blank=True, max_length=100)),
                ('total_family_members', models.IntegerField()),
                ('total_male_members', models.IntegerField()),
                ('no_of_children', models.IntegerField()),
                ('literate_members', models.IntegerField()),
                ('no_of_members_eligible_to_caste_vote', models.IntegerField()),
                ('members_above_sixty_years', models.IntegerField()),
                ('ward_no', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=9, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=9, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
